# Default values for alertmanager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: quay.io/prometheus/alertmanager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
# Chart name override. The full name is calculated as (release name + chart name)
nameOverride: ""
# Full name override is basically the full name override of the calculated (release name + chart name)
fullnameOverride: ""

alertmanagerConfigMatcherStrategy: {}
  # type: OnNamespace
  # # OR
  # type: None

alertmanagerConfigNamespaceSelector: {}
  # matchLabels:
  #   foo: bar
  #   baz: bax
  # # OR
  # matchExpressions:
  # - key: key1
  #   operator: In
  #   values:
  #   - value1
  # - key: key2
  #   operator: Exists
  # - key: key3
  #   operator: NotIn
  #   values:
  #   - value3

alertmanagerConfigSelector: {}
  # matchLabels:
  #   foo: bar
  #   baz: bax
  # # OR
  # matchExpressions:
  # - key: key1
  #   operator: In
  #   values:
  #   - value1
  # - key: key2
  #   operator: Exists
  # - key: key3
  #   operator: NotIn
  #   values:
  #   - value3

alertmanagerConfiguration: {}
  # name: some-alertmanager-config-custom-resource-name
  # global:
  #   # Example
  #   httpConfig:
  #     authorization:
  #       type: Bearer
  #       credentials:
  #         secret: alertmanager-authz-cred
  #         key: credential
  # templates:
  # - configMap:
  #     key: template
  #     name: alertmanager-template
  # - secret:
  #     key: template
  #     name: alertmanager-template

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
    # annotationKey1: annotationValue1
    # annotationKey2: annotationValue2
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
  # annotationKey1: annotationValue1
  # annotationKey2: annotationValue2

podLabels: {}
  # labelKey1: labelValue1
  # labelKey2: labelValue2

podSecurityContext: {}
  # # Example for podSecurityContext:
  # fsGroup: 2000
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Alertmanager pod definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Alertmanager pod definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

# NodeSelector is Kubernetes NodeSelector definition that should be applied to all Alertmanager Pods. default: {}
nodeSelector: {}
  # disktype: ssd
  # nodeLabelKey1: nodeLabelValue1
  # nodeLabelKey2: nodeLabelValue2

tolerations: []
  # - key: "key1"
  #   operator: "Equal"
  #   value: "value1"
  #   effect: "NoSchedule"
  # - key: "key1"
  #   operator: "Exists"
  #   effect: "NoSchedule"

# Affinity is a group of affinity scheduling rules applied to all Vault Pods. default: {}
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: zone
  #         operator: NotIn
  #         values:
  #         - zoneC

topologySpreadConstraints: []
  # - maxSkew: 1
  #   topologyKey: zone
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchLabels:
  #       foo: bar
  # - maxSkew: 1
  #   topologyKey: node
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchLabels:
  #       foo: bar

metrics:
  enabled: true
