{{- if gt (int .Values.replicaCount) 1 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  name: {{ include "alertmanager.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "alertmanager.pod.selectorLabels" . | nindent 6 }}
{{- end }}
