{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  name: {{ include "alertmanager.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels:
      {{- include "alertmanager.selectorLabels" . | nindent 6 }}
{{- end }}
