apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    {{- include "alertmanager.pod.selectorLabels" . | nindent 4 }}
